### ISSUE TITLE
Provide an open source license

### ISSUE THREAD

**Issue by paulocsanz** [cemarciano/Interactive-Flowchart#6]
E ai Cadu! ;)

Hey it would be really useful if you could provide a open source license with this project, so that usage cannot be contested.

We currently have a fork of it at [gramio-eci/grade](https://github.com/gremio-eci/grade) that has been extended to accept Farmácia at UFRJ, but without the license it's not clear if we can make something derived from it.

We also plan to support all graduation courses of UFRJ using SIGA's API, like SigaCalmo (https://github.com/gremio-eci/siga-calmo) does. We already have reverse engineered the API at [dantasb/siga-livre](https://github.com/DantasB/Siga-Livre/), so being sure we are authorized to extend this code would be great.

We are happy with the open source license of your choice, although we would recommend AGPL so we can ensure this code cannot be changed without the update being posted online to contribute back with the community. But MIT, Apache or BSD 3 can also be a possibility too.

**Comment by cemarciano** [comment]
Opa! :) Thank you for your concern! I will add the appropriate open source license tomorrow, first thing in the morning.
